--- 
before_script: 
  - "cd $TEST_DIR"
  - "npm install"
env: 
  - "TEST_DIR= my-api"
  - "TEST_DIR= mithril_front-end"
language: node_js
node_js: 
  - "7"
  - "8"
script: 
  - "npm run lint"