--- 
before_script: 
  - "cd $TEST_DIR"
  - "npm install"
env: 
  - TEST_DIR=mithril_front-end
  - TEST_DIR=my-api
language: node_js
node_js: 
  - "8"
  - "7"
script: 
  - "tslint -p tsconfig.json -c tslint.json"
  